export const OngoingList = [
  {
    id: '1',
    image: require('../assets/images/istockphoto-1158578874-612x612.jpg'),
    firstFoodName: 'Dal',
    secondFoodName: '2 Roti',
    thirdFoodName: 'Rice',
    fourthFoodName: 'Sabji',
    price: '₹120',
    tiffinHeadig: "Today's Veg Tiffin",
  },
  {
    id: '2',
    image: require('../assets/images/istockphoto-1158578874-612x612.jpg'),
    firstFoodName: 'Dal',
    secondFoodName: '2 Roti',
    thirdFoodName: 'Rice',
    fourthFoodName: 'Sabji',
    price: '₹120',
    tiffinHeadig: "Today's Veg Tiffin",
  },
  {
    id: '3',
    image: require('../assets/images/istockphoto-1158578874-612x612.jpg'),
    firstFoodName: 'Dal',
    secondFoodName: '2 Roti',
    thirdFoodName: 'Rice',
    fourthFoodName: 'Sabji',
    price: '₹120',
    tiffinHeadig: "Today's Veg Tiffin",
  },
];

export const HistoryList = [
  {
    id: '1',
    image: require('../assets/images/butterChiken.jpg'),
    firstFoodName: 'Butter Chicken',
    secondFoodName: '2 Roti',
    thirdFoodName: 'Rice',
    fourthFoodName: '1 Egg',
    price: '₹150',
    tiffinHeadig: "Today's Non-Veg Tiffin",
    status: 'Completed',
    date: '26 Jan',
    time: '12:20 pm',
  },
  {
    id: '2',
    image: require('../assets/images/butterChiken.jpg'),
    firstFoodName: 'Butter Chicken',
    secondFoodName: '2 Roti',
    thirdFoodName: 'Rice',
    fourthFoodName: '1 Egg',
    price: '₹150',
    tiffinHeadig: "Today's Non-Veg Tiffin",
    status: 'Canceled',
    date: '26 Jan',
    time: '12:20 pm',
  },
  {
    id: '3',
    image: require('../assets/images/butterChiken.jpg'),
    firstFoodName: 'Butter Chicken',
    secondFoodName: '2 Roti',
    thirdFoodName: 'Rice',
    fourthFoodName: '1 Egg',
    price: '₹150',
    tiffinHeadig: "Today's Non-Veg Tiffin",
    status: 'Completed',
    date: '26 Jan',
    time: '12:20 pm',
  },
];
